---
project: 'project_name'
Data_type: 'CITESeq'
SC_scripts: '/hpcdata/vrc/vrc1_data/douek_lab/snakemakes/SingleCell/scripts/'
CITESeq_scripts: '/hpcdata/vrc/vrc1_data/douek_lab/snakemakes/SingleCell/CITESeq/scripts/'
runs_dir: '/hpcdata/vrc/vrc1_data/douek_lab/Runs/'
sample_sheet: 'Sample_sheet.csv' 
QC_name: 'todays_date'
QC_file: 'QC_steps/QC_steps.csv'
batch: 'Batch_name'
comparison_file: 'Test_comparisons.csv'
species: 'hsapiens'
tissue: 'pbmc'
refgtf: '/hpcdata/vrc/vrc1_data/douek_lab/reference_sets/hg38/Annotation/Genes/Homo_sapiens.GRCh38.92.chr.gtf'
hashed: 'True'
dehash_method: 'Trough'
dehash_method_comparisons: 'Trough,MULTIseqDemux'
isotype_controls: 'IgG1.m.isotype,IgG2a.m.isotype,IgG2b.m.isotype,IgG2b.r.isotype'
